export const INIT_COMMENTS = 'INIT_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_WISH_COMMENT = 'ADD_WISH_COMMENT';
export const REMOVE_WISH_COMMENT = 'REMOVE_WISH_COMMENT';
export const SET_COMMENTS = 'SET_COMMENTS';
